# Settings for the Makefile which define
# various things like the names, paths, etc pp
#

# GRF Name
GRF_NAME        = 32bpp_extra
GRF_FILENAME    = 32bpp_extra
GRF_SHORTNAME   = 32bpp_extra
GRF_NIGHTLYNAME = nightly
GRF_PALETTE	    = Windows
GRF_ORIGIN      = default = Please redownload from official source.

LICENSE_FILENAME   = docs/license.ptxt
CHANGELOG_FILENAME = docs/changelog.ptxt
README_FILENAME    = docs/readme.ptxt
DESC_FILENAME      = docs/descriptions.ptxt

# Build parameters and programmes
# Usually this needs no change.
NFORENUM_FLAGS =
GRFCODEC_FLAGS = -e -p 2
TAR_FLAGS      = cf
ZIP_FLAGS      = -r
BZIP_FLAGS     = -k9f
CC_FLAGS       = -C -E - <

# Macs have a different md5 command than linux or mingw envirnoment:
ifeq ($(OSTYPE),Darwin)
MD5SUM   = md5 -r
else
MD5SUM   = md5sum
endif

NFORENUM = renum
GRFCODEC = grfcodec
TAR      = tar
ZIP      = zip
BZIP     = bzip2
MAKE     = make
CC       = gcc
UNIX2DOS = unix2dos

PNFO_SUFFIX  = pnfo
NFO_SUFFIX   = nfo
TAR_SUFFIX   = tar
GRF_SUFFIX   = grf
ZIP_SUFFIX   = zip
BZIP2_SUFFIX = bz2
TXT_SUFFIX   = txt
PTXT_SUFFIX  = ptxt
DEP_SUFFIX   = dep

# Things to replace in the readme file
GRF_TITLE_DUMMY = {{GRF_TITLE}}
REVISION_DUMMY  = {{GRF_REVISION}}

# Paths defining the directory layout
SPRITEDIR       = sprites
DOCDIR          = docs

MAINDIRS       = $(SPRITEDIR) $(DOCDIR)
PNFO_FILENAME  = $(addprefix $(SPRITEDIR)/,$(addsuffix .$(PNFO_SUFFIX),$(GRF_FILENAME)))
NFO_FILENAME   = $(addprefix $(SPRITEDIR)/,$(addsuffix .$(NFO_SUFFIX),$(GRF_FILENAME)))
REV_FILENAME   = REV

GRF_TITLE     = $(GRF_NAME) $(VERSION_STRING)

DOC_FILENAMES = $(addsuffix .$(TXT_SUFFIX),$(basename $(LICENSE_FILENAME) $(CHANGELOG_FILENAME) $(README_FILENAME)))

BUNDLE_FILES  = $(GRF_FILENAME).$(GRF_SUFFIX) $(DOC_FILENAMES)

# Remove the @ when you want a more verbose output.
_V := @
_E := @echo
